### ISSUE TITLE
[ Feature ] REST endpoint 

### ISSUE THREAD

**Issue by Earu** [Energizers/Sulfur#4]
Create REST endpoint that takes a file url (for example a Discord attachment url).

**Comment by logotie** [comment]
Hey dude, thanks for the quick info on the chat :)

The summary in the beginning is for a POST API that accepts a torrent file.
The API requires an authorization token and returns a JSON with an Id?

Just want to confirm, thanks!

**Comment by Earu** [comment]
@logotie You got it 👍

**Comment by logotie** [comment]
Alright, do you mean like a download link please?

**Comment by Earu** [comment]
A download link is fine. Heres are examples:
Multiple files: https://cdn.discordapp.com/attachments/347158494383702016/591997675134517298/HorribleSubs_Kill_la_Kill_01-24_1080p_Batch.torrent

Single file: https://cdn.discordapp.com/attachments/347158494383702016/591997490786598932/ubuntu-19.04-desktop-amd64.iso.torrent

**Comment by Earu** [comment]
Im also gonna link this https://github.com/Energizers/Sulfur/issues/2 because its relevant to what you're going to do

**Comment by logotie** [comment]
Thank you very much will do, I will focus on these 2 tasks:
1.  Post API that accepts only a torrent link.
2.  Post API that accepts only a torrent link and an authorization token.
3.  Post API that accepts the stuff mentioned above and returns a GUID.

Hope that's ok?

**Comment by Earu** [comment]
> 
> 
> Thank you very much will do, I will focus on these 2 tasks:
> 
>     1. Post API that accepts only a torrent link.
> 
>     2. Post API that accepts only a torrent link and an authorization token.
> 
>     3. Post API that accepts the stuff mentioned above and returns a GUID.
> 
> 
> Hope that's ok?

This should be one endpoint, we wont accept non-authorized requests, we also always want to get the GUID.

To put it simply your endpoint takes a download link to a torrent, an authorization token and returns a payload containing a GUID.

**Comment by logotie** [comment]
> > Thank you very much will do, I will focus on these 2 tasks:
> > ```
> > 1. Post API that accepts only a torrent link.
> > 
> > 2. Post API that accepts only a torrent link and an authorization token.
> > 
> > 3. Post API that accepts the stuff mentioned above and returns a GUID.
> > ```
> > 
> > 
> > Hope that's ok?
> 
> This should be one endpoint, we wont accept non-authorized requests, we also always want to get the GUID everytime.
> 
> To put it simply your endpoint takes a download link to a torrent, an authorization token and returns a payload containing a GUID.

Apologies, the way I phrased it wasn't accurate.  I listed numerically how I would build the single one API, starting from its most basic functionality to the somewhat complete one.

I will get started :)

**Comment by logotie** [comment]
Further clarification:

![image](https://user-images.githubusercontent.com/26583547/60130145-96a42200-978e-11e9-957d-d056b76b8e6c.png)

Receives through a POST request -->
{
"url":"google.com"
}

Responds with -->
{
"id":"guid here"
}

**Comment by Earu** [comment]
Merged https://github.com/Energizers/Sulfur/pull/5
